include:
  - path: platform/docker-compose.platform.yml
    env_file:
      - env/platform.env
      - env/shared.env
  - path: pretix/docker-compose.pretix.yml
    env_file:
      - env/backup.env
      - env/metrics.env
      - env/pretix.env
      - env/shared.env
  - path: websites/docker-compose.websites.yml
    env_file:
      - env/backup.env
      - env/metrics.env
      - env/shared.env
      - env/websites.env
  - path: vault/docker-compose.vault.yml
    env_file:
      - env/backup.env
      - env/shared.env
      - env/vault.env
