global:
  scrape_interval: 15s

scrape_configs:
  - job_name: platform
    static_configs:
      - targets:
        - platform_node_exporter:9100
        - platform_caddy:2019
  - job_name: targets
    fallback_scrape_protocol: PrometheusText1.0.0
    file_sd_configs:
      - files:
        - /etc/prometheus/config/*.targets.yml
