import { ALUMNI_CONFIGS, SECTION_CONFIGS } from '../config.ts';

const CONFIG = [...ALUMNI_CONFIGS, ...SECTION_CONFIGS];

const parseRedirects = (redirects: string[]) =>
  redirects.map((redirect) => `, www.${redirect}, ${redirect}`).join('');

export const buildCaddyfile = async () => {
  let caddyfile = '# GENERATED BY `buildCaddyfile.ts`\n';
  caddyfile += 'www.{$URL} {\n';
  caddyfile += '    import hardened_security\n';
  caddyfile += '    redir https://{$URL}{uri} permanent\n';
  caddyfile += '}\n\n';
  caddyfile += '{$URL} {\n';
  caddyfile += '    import hardened_security\n';
  caddyfile += '    root * /srv/@\n';
  caddyfile += '    try_files {path} /index.html\n';
  caddyfile += '    file_server\n';
  caddyfile += '}\n';

  for (const { cname, redirects = [] } of CONFIG) {
    caddyfile += '\n';
    caddyfile += `www.${cname}.{$URL}${parseRedirects(redirects)} {\n`;
    caddyfile += '    import hardened_security\n';
    caddyfile += `    redir https://${cname}.{$URL}{uri} permanent\n`;
    caddyfile += '}\n\n';
    caddyfile += `${cname}.{$URL} {\n`;
    caddyfile += '    import hardened_security\n';
    caddyfile += `    root * /srv/${cname}\n`;
    caddyfile += '    try_files {path} /index.html\n';
    caddyfile += '    file_server\n';
    caddyfile += '}\n';
  }

  await Bun.write('./dist/Caddyfile', caddyfile);
};
